blog/urls.py
from django.urls import path
from .views import views

# imagenes
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path("", views.index, name="index",),
    path("articles/", views.ArticlesView.as_view(), name="Artículos",),
    path("about/", views.about, name="Sobre Mi",),
    path("results/", views.searchResults, name="Resultados",),
    path("create_article/", views.ArticleCreateView.as_view(), name="Crear Artículo",),
    path("article/<int:pk>/detalle", views.ArticleDetails.as_view(), name="Detalle Artículo",),
    path("article/<int:pk>/editar", views.ArticleUpdate.as_view(), name="Editar Artículo",),
    path("article/<int:pk>/eliminar", views.ArticleDelete.as_view(), name="Eliminar Artículo",),
    path("news/", views.NewsViews.as_view(), name="Noticias",),
    path("create_comment/<int:pk>", views.CommentCreateView.as_view(), name="Crear Comentario",),
    path("delete_comment/<int:pk>", views.CommentDelete.as_view(), name="Eliminar Comentario",),
    path("update_comment/<int:pk>", views.CommentUpdate.as_view(), name="Editar Comentario",),
    path("news/<int:pk>/editar", views.NewsUpdate.as_view(), name="Editar Noticia",),
    path("news/<int:pk>/eliminar", views.NewsDelete.as_view(), name="Eliminar Noticia",),
    path("news/<int:pk>/detalle", views.NewsDetails.as_view(), name="Detalle Noticia",),
    path("create_news/", views.NewsCreateView.as_view(), name="Crear Noticia",),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls"), name='blog'),
    path('', include("users.urls"), name='users'),
    path("__reload__/", include("django_browser_reload.urls")),
    
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Articulo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    titulo = models.CharField(max_length=40)
    subtitulo = models.CharField(max_length=30)
    cuerpo = RichTextField()
    fecha = models.DateTimeField(auto_now_add=True, editable=False)
    imagen = models.ImageField(upload_to='post_imgs/', null=True, blank=True)
    

    def __str__(self) -> str:
        return self.titulo + " - " + self.subtitulo
    
    class Meta:
        ordering = ["titulo", "fecha"]

    
    
class Comentario(models.Model):
    user = models.ForeignKey(User, editable=False, null=True, on_delete=models.SET_NULL)
    comment = models.ForeignKey(Articulo, related_name="comentarios", on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=20)
    cuerpo = RichTextField()
    fecha = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        ordering = ['-fecha']

    def __str__(self):
        return '%s - %s - %s' % (self.titulo, self.cuerpo, self.user)
    

    def __str__(self) -> str:
        return '%s - %s' % (self.user, self.titulo)
    
    class Meta:
        ordering = ["titulo", "fecha"]
    
class Noticia(models.Model):
    titulo = models.CharField(max_length=30)
    cuerpo = RichTextField()
    fecha = models.DateTimeField(auto_now_add=True, editable=False)
    

    def __str__(self) -> str:
        return self.titulo

blog/forms.py
from django import forms
from .models import Articulo, Comentario, Noticia


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = "__all__"

class ComentaryForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = "__all__"

class NewsForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = "__all__"

class SearchArticle(forms.Form):
    titulo = forms.CharField(required=False)

blog/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.forms import AuthenticationForm
# from django.contrib.auth import login, authenticate
# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin



# Create your views here.
def index(request):
    return render(request, "index.html")

class ArticlesView(LoginRequiredMixin, ListView):
    model = Articulo
    context_object_name = "articulo"
    template_name = "articles.html"

def about(request):
    return render(request, "about.html")

class NewsDetails(LoginRequiredMixin, DetailView):
    model = Noticia
    context_object_name = "noticia"
    template_name = "details_news.html"

class NewsViews(LoginRequiredMixin, ListView):
    model = Noticia
    context_object_name = "noticia"
    template_name = "news.html"

class NewsUpdate(UserPassesTestMixin, UpdateView):
    model = Noticia
    template_name = "update_news.html"
    success_url = reverse_lazy("Noticias")
    fields = ["titulo", "cuerpo"]

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

class NewsDelete(UserPassesTestMixin, DeleteView):
    model = Noticia
    template_name = "delete_news.html"
    success_url = reverse_lazy("Noticias")

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

class ArticleCreateView(UserPassesTestMixin, CreateView):
    model = Articulo
    template_name = 'create_article.html'
    fields = ["titulo", "subtitulo", "cuerpo", 'imagen']
    success_url = reverse_lazy("Artículos")

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)
    
    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

class ArticleUpdate(UserPassesTestMixin, UpdateView):
    model = Articulo
    template_name = "update_article.html"
    success_url = reverse_lazy("Artículos")
    fields = ["titulo", "subtitulo", "cuerpo", "imagen"]

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

class ArticleDelete(UserPassesTestMixin, DeleteView):
    model = Articulo
    template_name = "delete_article.html"
    success_url = reverse_lazy("Artículos")

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

class ArticleDetails(LoginRequiredMixin, DetailView):
    model = Articulo
    context_object_name = "articulo"
    template_name = "details_article.html"

class NewsCreateView(UserPassesTestMixin, CreateView):
    model = Noticia
    template_name = 'create_news.html'
    fields = ["titulo", "cuerpo"]
    success_url = reverse_lazy("Noticias")

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comentario
    template_name = 'delete_comment.html'

    
    def get_success_url(self) -> str:
        return reverse('Detalle Artículo', kwargs={'pk': self.object.comment_id})

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comentario
    template_name = 'update_comment.html'
    fields = ['titulo', 'cuerpo']

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        if obj.user != self.request.user:
            raise PermissionError("No tiene permisos para editar este elemento!")
        return obj
    
    def get_success_url(self) -> str:
        return reverse('Detalle Artículo', kwargs={'pk': self.object.comment_id})


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comentario
    template_name = 'create_comment.html'
    fields = ["titulo", "cuerpo"]

    def form_valid(self, form):
        form.instance.comment_id = self.kwargs['pk']
        self.pk = form.instance.comment_id
        form.instance.user = self.request.user
        return super(CommentCreateView, self).form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse('Detalle Artículo', kwargs={'pk': self.pk})

# buscador
@login_required
def searchResults(request):
    articulo = []
    form = SearchArticle(request.GET)
    if form.is_valid():
        titulo = form.cleaned_data.get('titulo')

        if titulo:
            articulo = Articulo.objects.filter(titulo__icontains=titulo)

    return render(request, 'searchResults.html', {'form': form, 'articulo': articulo})

blog/templates/about.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 rounded-xl">
  <div class="py-20 bg-blue-500 mb-10">
    <label class="text-5xl text-white font-bold shadow-black drop-shadow-lg">Sobre Mí</label>
  </div>
  <div class="m-5 mx-60 text-2xl flex flex-col gap-5">
    <img class="w-80 rounded-xl mx-auto" src="../../media/48396333.jpg" alt="foto_de_perfil_nestor" />
    <p class="text-left">
      En este momento me estoy formando como programador con la meta de
      convertirme en un desarrollador Full-Stack. Junto con este curso estoy
      realizando la segunda etapa del Argentina Programa 4.0 y realizando
      proyectos por mi cuenta para no dejar de aprender sobre las diferentes
      tecnologías y herramientas disponibles a los desarrolladores.</p>
      
      <p class="text-left">
      En este proyecto, aparte de Python y Django, implementé Tailwind CSS 
      para aplicar los estilos a los elementos de la página de una manera
      más dinámica y ágil. Si bien estoy muy conforme con el proyecto,
      quedan funcionalidades pendientes por agregar para decir que 
      se encuentra completo(permitir a los usuarios eliminar su cuenta,
      mensajes directos entre usuarios, integración con redes sociales, etc.)
      </p>
    </p>
  </div>
</main>
{% endblock %}

blog/templates/articles.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 rounded-xl">
  <div class="py-20 bg-amber-500 mb-10">
    <label class="text-5xl text-white font-bold shadow-black drop-shadow-lg">Artículos</label>
  </div>
  {% if request.user.is_superuser %}
    <a href="{% url 'Crear Artículo' %}"
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-2"
    >Nuevo Artículo
    </a>
  {% endif %}
  <ul class="px-60 py-5">
    {% for a in articulo %}
    <li class="my-10 pb-10 border-b-2 w-4/5 mx-auto border-gray-400">
      <h2 class="text-4xl mb-5 text-left font-bold">
      {{a.titulo}}
      </h2>
      <h3 class="text-3xl text-left">{{a.subtitulo}}</h3>
      <div class="text-left"><small>Autor: {{a.user}}</small></div>
      <div class="text-left"><small>Fecha de Publicación: {{a.fecha}}</small></div>
      {% if a.imagen %}
      <img src="{{a.imagen.url}}" alt="{{a.titulo}}">
      {% endif %}
      <div class="text-left">
        <p class="mt-5">{{a.cuerpo | slice:":250" | safe }}...</p>
      </div>
      <ul class="flex gap-3 place-content-center">
        <a href="{% url "Detalle Artículo" a.pk %}"
          class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
        >Leer más
        </a>
        {% if request.user.is_superuser %}
          <a href="{% url "Editar Artículo" a.pk %}"
            class="bg-green-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
          >Editar
          </a>
          <a href="{% url "Eliminar Artículo" a.pk %}"
            class="bg-red-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
          >Eliminar
          </a>
          {% endif %}
      </ul>
    </li>
     {% endfor %}
  </ul>
</main>
{% endblock %}

blog/templates/create_article.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}

<main class="text-center m-10 bg-slate-200 p-10 rounded-xl">
  <h2 class="text-3xl">Nuevo Artículo</h2>

  <ul>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form.media }}
      <li class="mt-5"><label for="">Título</label></li>
      <li>
        <input type="text" name="titulo" id="id_titulo" style="width: 400px" />
      </li>
      <li class="mt-5"><label for="">Subtitulo</label></li>
      <li>
        <input
          type="text"
          name="subtitulo"
          id="id_subtitulo"
          style="width: 400px"
        />
      </li>
      <li class="mt-5"></li>
      <li class="my-5">
        <label for="">Imagen:</label>
        {{form.imagen}}
      </li>
      <li>{{form.cuerpo}}</li>

      <div class="flex gap-3 justify-center">
        <button
          action="submit"
          class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
        >
          Publicar
        </button>
        <a
          href="{% url 'Artículos' %}"
          class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
          >Volver
        </a>
      </div>
    </form>
  </ul>
</main>
{% endblock %}

blog/templates/create_comment.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 p-10 rounded-xl">
  <h2>Nuevo Comentario</h2>

  <ul>
    <form method="post">
      {% csrf_token %} {{form.media}}
      <li class="my-10">
        <label for="">Autor: {{user}}</label>
        <label class="mx-5">Título:</label>
        <input type="text" name="titulo" id="id_titulo" style="width: 400px" />
      </li>
      <li>{{form.cuerpo}}</li>
      <li class="pt-10">
        <button
          action="submit"
          class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
        >
          Enviar
        </button>
        <input
        type=button
        value='Volver'
        onClick="javascript:history.go(-1);"
        class="bg-indigo-500 hover:cursor-pointer shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
        >
        </input>
      </li>
    </form>
  </ul>
</main>
{% endblock %}

blog/templates/create_news.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 p-10 rounded-xl">
  <h1>Sección Crear Noticia</h1>
  <h2>Crear Noticia</h2>

  <ul>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{form.media}}
      <li class="my-10">
        <label for="">Título</label>
        <input type="text" name="titulo" id="id_titulo" style="width: 400px" />
      </li>
      <li>
        <label for="">Texto</label>
      </li>
      <li>{{form.cuerpo}}</li>
      <button
        class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
      >
        <a action="submit">Guardar</a>
      </button>
    </form>
  </ul>
</main>
{% endblock %}

blog/templates/delete_article.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 p-10 bg-slate-200 rounded-xl">
  <form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <strong class="text-3xl">
      Esta seguro que desea eliminar el artículo: 
    </strong>
    <h1 class="text-3xl font-bold">{{articulo.titulo}}</h1>
    <p class="text-2xl">
      <strong for="html">Cuerpo del artículo:</strong>
      <div class="text-3xl">{{articulo.cuerpo | slice:":200" | safe }}...</div>
    </p>
    <button
      class="bg-red-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
    >
      Eliminar
    </button>
    <button
    class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
    <a href="{% url "Artículos" %}">Volver</a>
  </button>
  </form>
</main>
{% endblock %}

blog/templates/delete_news.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 rounded-xl">
  <h1>Editar Noticia</h1>
  <form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <h1>Esta seguro que desea eliminar la noticia: {{noticia.titulo}}</h1>
    <button
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
    >
      Eliminar
    </button>
    <button
    class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
    <a href="{% url "Noticias" %}">Volver</a>
  </button>
  </form>
</main>
{% endblock %}

blog/templates/details_news.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 rounded-xl">
  <div class="py-20 bg-green-500 mb-10">
    <label class="text-5xl text-white font-bold shadow-black drop-shadow-lg">{{noticia.titulo}}</label>
  </div>
  <form class="p-10" action="" method="POST">
    {% csrf_token %}

    <h1 class="text-2xl">{{noticia.fecha}}</h1>
    <div class="p-10 text-3xl mx-32 text-left">{{noticia.cuerpo | safe }}</div>
    
    <button
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
    >
      <a href="{% url "Noticias" %}">Volver</a>
    </button>
  </form>
</main>
{% endblock %}

blog/templates/news.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center flex flex-col gap-5 m-10 bg-slate-200 rounded-xl">
  <div class="py-20 bg-green-500 mb-10">
    <label class="text-5xl text-white font-bold shadow-black drop-shadow-lg">Noticias</label>
  </div>
  
  {% if request.user.is_superuser %}
  <div>
    <a class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5" href="{% url 'Crear Noticia' %}">Nueva Noticia</a>
  </div>
  {% endif %}

<ul class="px-60 py-5">
  {% if noticia %}
  <ul class="px-30 py-5">
    {% for n in noticia %}
    <li><h2 class="text-5xl mb-5 text-left">{{n.titulo}}</h2></li>
    <div class="text-left text-2xl"><small>{{n.fecha}}</small></div>
    <li class="mt-5 text-left text-2xl my-10">{{n.cuerpo | safe | slice:":100" }}...</li>
    <p>
      <button
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
    >
      <a href="{% url 'Detalle Noticia' n.pk %}">Leer más</a>
    </button>
    {% if request.user.is_superuser %}
    <button
    class="bg-green-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
    >
    <a href="{% url 'Editar Noticia' n.pk %}">Editar</a>
    </button>
    <button
    class="bg-red-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
    > 
    <a href="{% url 'Eliminar Noticia' n.pk %}">Eliminar</a>
    </button>
    {% endif %}
    </p>
    {% endfor %}
  </ul>
    {% else %}
    <p class="text-3xl">Aún no hay noticias</p>
  {% endif %}
</main>
{% endblock %}

blog/templates/searchResults.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 bg-slate-200 p-10 rounded-xl">
  <div class="flex flex-col gap-5">
    <h2 class="text-3xl">
      Mostrando {{articulo | length}} resultados para: {{form.titulo.value}}
    </h2>
    {% if articulo %}
    <ul>
      {% for art in articulo %}
      <li class="flex flex-col gap-2 py-5 border-2 border-black rounded-xl m-3">
        <a
          class="text-3xl text-blue-500"
          href="{% url 'Detalle Artículo' art.pk %}"
          >{{ art.titulo }}</a
        >
        <h4>{{ art.subtitulo }} - {{ art.fecha }}</h4>
        <p>{{art.cuerpo | slice:":80" | safe}}...</p>
      </li>
      {% endfor %}
    </ul>
    {% endif %}
    <a
      href="{% url 'Artículos' %}"
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
      >Volver
    </a>
  </div>
</main>
{% endblock %}

blog/templates/update_article.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 p-10 bg-slate-200 rounded-xl">
  <h1 class="text-3xl p-5">Editar Artículo</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form.media}} 
    <div class="flex flex-col gap-3">
      {{form.as_div}}
    </div>
    <button
    class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
    Guardar Cambios
  </button>
    <button
    class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
    <a href="{% url "Artículos" %}">Volver</a>
  </button>
  </form>
</main>
{% endblock %}

blog/templates/update_comment.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 p-10 bg-slate-200 rounded-xl">
  <h1 class="text-2xl p-5">Editar Comentario</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form.media}}
    <ul class="flex flex-col gap-3">
        <li>
        <label>Título: </label>
        {{form.titulo}}
        </li>
        <li>{{form.cuerpo}}</li>
    </ul>
    <button
    class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
    Guardar Cambios
  </button>
  <input
  type=button
  value='Volver'
  onClick="javascript:history.go(-1);"
  class="bg-indigo-500 hover:cursor-pointer shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
  </input>
  </form>
</main>
{% endblock %}

blog/templates/update_news.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 p-10 bg-slate-200 rounded-xl">
  <h1 class="text-3xl p-5">Editar Noticia</h1>
  <form action="" method="POST">
    {% csrf_token %} {{form.media}} {{form.as_p}}
    <button
    class="bg-green-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
  >
   Guardar Cambios
  </button>
  <button
  class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
>
  <a href="{% url "Noticias" %}">Volver</a>
</button>
  </form>
</main>
{% endblock %}

blog/templates/update_profile.html
{% extends "./index.html" %} {% load static tailwind_tags %} {% block content %}
<main class="text-center m-10 p-10 bg-slate-200 rounded-xl">
  <h1 class="text-3xl">Editar Perfil</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form.media}}
    <div class="flex flex-col gap-4 p-10 place-items-center">
      {% if request.user.avatar.imagen %}
      <img class="w-40 h-40 rounded-full" src="{{request.user.avatar.imagen.url}}" alt="{{request.user.avatar.imagen}}">
      {% else %}
      <label for="html">Todavía no elegiste un avatar</label>
      {% endif %}
      <span>Avatar</span>
    </div>
    <div>
      <ul class="flex flex-col-reverse gap-5 items-center">
        <li class="translate-x-2">
          <label class="pr-5 align-top" for="">Descripción:</label>
          {{form.media}}
          {{form.descripcion}}
        </li>
        <li class="-translate-x-5">
          <label class="pr-5" for="">URL Personal:</label>
          {{form.link}}
        </li>
        <li class="translate-x-2">
          <label class="pr-5" for="">Email:</label>
          {{form.email}}
        </li>
        <li class="translate-x-5">
          <label class="pr-5" for="">Cambiar Avatar:</label>
          {{form.imagen}}
        </li>
        <li>
          <label class="pr-5" for="">Apellido:</label>
          {{form.last_name}}
        </li>
        <li>
          <label class="pr-5" for="">Nombre:</label>
          {{form.first_name}}
        </li>
      </ul>
      <button type="submit"
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
      >
        Guardar Cambios
      </button>
      <button
      class="bg-indigo-500 shadow-lg p-2 rounded-md text-white hover:bg-white hover:text-black mt-5"
      >
        <a href="{% url "Perfil" %}">Volver</a>
      </button>
    </div>
      
      
  </form>
</main>
{% endblock %}